name: "Build Python Package"
description: "Build the package to upload to pypi."

runs:
  using: "composite"
  steps:
    # Minimum supported version is Python 3.7
    - name: Use Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Pip cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-build-vsix-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-build-vsix-

    - name: Upgrade Pip
      run: python -m pip install -U pip
      shell: bash

    # For faster/better builds of sdists.
    - name: Install build pre-requisite
      run: python -m pip install wheel
      shell: bash

    - name: Install nox
      run: python -m pip install nox
      shell: bash

    - name: Build sdist and wheels
      run: python -m nox --session build
      shell: bash

    - name: Upload Packages to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pypi-packages
        path: |
          packages/python/dist/*.gz
          packages/python/dist/*.whl
        if-no-files-found: error
        retention-days: 7
