// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

namespace LSProtocol {
    /// <summary>
    /// Completion item tags are extra annotations that tweak the rendering of a completion
    /// item.
    /// 
    /// @since 3.15.0
    /// </summary>
    public enum CompletionItemTag 
    {
        /// <summary>
        /// Render a completion as obsolete, usually using a strike-out.
        /// </summary>
        Deprecated = 1,

    }
}
