// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

namespace LSProtocol {
    /// <summary>
    /// A document highlight kind.
    /// </summary>
    public enum DocumentHighlightKind 
    {
        /// <summary>
        /// A textual occurrence.
        /// </summary>
        Text = 1,

        /// <summary>
        /// Read-access of a symbol, like reading a variable.
        /// </summary>
        Read = 2,

        /// <summary>
        /// Write-access of a symbol, like writing to a variable.
        /// </summary>
        Write = 3,

    }
}
