// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

namespace LSProtocol {
    /// <summary>
    /// Predefined error codes.
    /// </summary>
    public enum ErrorCodes 
    {
        ParseError = -32700,

        InvalidRequest = -32600,

        MethodNotFound = -32601,

        InvalidParams = -32602,

        InternalError = -32603,

        /// <summary>
        /// Error code indicating that a server received a notification or
        /// request before the server has received the `initialize` request.
        /// </summary>
        ServerNotInitialized = -32002,

        UnknownErrorCode = -32001,

    }
}
