// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using System.Runtime.Serialization;

namespace LSProtocol {
    /// <summary>
    /// A pattern kind describing if a glob pattern matches a file a folder or
    /// both.
    /// 
    /// @since 3.16.0
    /// </summary>
    public enum FileOperationPatternKind 
    {
        /// <summary>
        /// The pattern matches a file only.
        /// </summary>
        [EnumMember(Value = "file")]File,

        /// <summary>
        /// The pattern matches a folder only.
        /// </summary>
        [EnumMember(Value = "folder")]Folder,

    }
}