// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT


namespace LSProtocol
{
    /// <summary>
    /// Inlay hint kinds.
    /// 
    /// </summary>
    public enum InlayHintKind
    {
        /// <summary>
        /// An inlay hint that for a type annotation.
        /// </summary>
        Type = 1,

        /// <summary>
        /// An inlay hint that is for a parameter.
        /// </summary>
        Parameter = 2,

    }
}
