// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using System.Runtime.Serialization;
using Newtonsoft.Json.Linq;

namespace LSProtocol {
    /// <summary>
    /// LSP arrays.
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public class LSPArray: JArray
    {
    }

}
