// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using System.Runtime.Serialization;

namespace LSProtocol {
    /// <summary>
    /// The LSP any type.
    /// Please note that strictly speaking a property with the value `undefined`
    /// can't be converted into JSON preserving the property name. However for
    /// convenience it is allowed and assumed that all these properties are
    /// optional as well.
    /// </summary>
    [Since("3.17.0")]
    [DataContract]
    public class LSPAny: object
    {
    }

}
