// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

namespace LSProtocol {
    /// <summary>
    /// A notebook cell kind.
    /// 
    /// @since 3.17.0
    /// </summary>
    public enum NotebookCellKind 
    {
        /// <summary>
        /// A markup-cell is formatted source that is used for display.
        /// </summary>
        Markup = 1,

        /// <summary>
        /// A code-cell is source code.
        /// </summary>
        Code = 2,

    }
}