// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

namespace LSProtocol {
    public enum PrepareSupportDefaultBehavior 
    {
        /// <summary>
        /// The client's default behavior is to select the identifier
        /// according the to language's syntax rule.
        /// </summary>
        Identifier = 1,

    }
}
