// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using System.Runtime.Serialization;

namespace LSProtocol {
    public enum ResourceOperationKind 
    {
        /// <summary>
        /// Supports creating new files and folders.
        /// </summary>
        [EnumMember(Value = "create")]Create,

        /// <summary>
        /// Supports renaming existing files and folders.
        /// </summary>
        [EnumMember(Value = "rename")]Rename,

        /// <summary>
        /// Supports deleting existing files and folders.
        /// </summary>
        [EnumMember(Value = "delete")]Delete,

    }
}
