// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using System.Runtime.Serialization;

namespace LSProtocol {
    /// <summary>
    /// A set of predefined token types. This set is not fixed
    /// an clients can specify additional token types via the
    /// corresponding client capabilities.
    /// 
    /// @since 3.16.0
    /// </summary>
    public enum SemanticTokenTypes 
    {
        /// <summary>
        /// </summary>
        [EnumMember(Value = "namespace")]Namespace,

        /// <summary>
        /// Represents a generic type. Acts as a fallback for types which can't be mapped to
        /// a specific type like class or enum.
        /// </summary>
        [EnumMember(Value = "type")]Type,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "class")]Class,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "enum")]Enum,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "interface")]Interface,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "struct")]Struct,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "typeParameter")]TypeParameter,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "parameter")]Parameter,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "variable")]Variable,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "property")]Property,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "enumMember")]EnumMember,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "event")]Event,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "function")]Function,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "method")]Method,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "macro")]Macro,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "keyword")]Keyword,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "modifier")]Modifier,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "comment")]Comment,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "string")]String,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "number")]Number,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "regexp")]Regexp,

        /// <summary>
        /// </summary>
        [EnumMember(Value = "operator")]Operator,

        /// <summary>
        /// @since 3.17.0
        /// </summary>
        [EnumMember(Value = "decorator")]Decorator,

    }
}