// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

namespace LSProtocol {
    /// <summary>
    /// How a signature help was triggered.
    /// 
    /// @since 3.15.0
    /// </summary>
    public enum SignatureHelpTriggerKind 
    {
        /// <summary>
        /// Signature help was invoked manually by the user or by a command.
        /// </summary>
        Invoked = 1,

        /// <summary>
        /// Signature help was triggered by a trigger character.
        /// </summary>
        TriggerCharacter = 2,

        /// <summary>
        /// Signature help was triggered by the cursor moving or by the document content changing.
        /// </summary>
        ContentChange = 3,

    }
}