// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT


namespace LSProtocol
{
    using System;

    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Property | AttributeTargets.Enum)]
    public class SinceAttribute : Attribute
    {
        public SinceAttribute()
        {
            Version = null;
        }

        public SinceAttribute(string version)
        {
            Version = version;
        }

        public string? Version { get; }
    }
}
