// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

namespace LSProtocol {
    /// <summary>
    /// Symbol tags are extra annotations that tweak the rendering of a symbol.
    /// 
    /// @since 3.16
    /// </summary>
    public enum SymbolTag 
    {
        /// <summary>
        /// Render a symbol as obsolete, usually using a strike-out.
        /// </summary>
        Deprecated = 1,

    }
}