// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using System.Runtime.Serialization;


namespace LSProtocol
{
    public enum TokenFormat
    {
        [EnumMember(Value = "relative")] Relative,

    }
}
