// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using System.Runtime.Serialization;

namespace LSProtocol {
    /// <summary>
    /// </summary>
    public enum TokenFormat 
    {
        /// <summary>
        /// </summary>
        [EnumMember(Value = "relative")]Relative,

    }
}