// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT

using System.Runtime.Serialization;


namespace LSProtocol
{
    public enum TraceValues
    {
        /// <summary>
        /// Turn tracing off.
        /// </summary>
        [EnumMember(Value = "off")] Off,

        /// <summary>
        /// Trace messages only.
        /// </summary>
        [EnumMember(Value = "messages")] Messages,

        /// <summary>
        /// Verbose message tracing.
        /// </summary>
        [EnumMember(Value = "verbose")] Verbose,

    }
}
