// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// 
// THIS FILE IS AUTOGENERATED, DO NOT MODIFY IT


namespace LSProtocol
{
    public enum WatchKind
    {
        /// <summary>
        /// Interested in create events.
        /// </summary>
        Create = 1,

        /// <summary>
        /// Interested in change events
        /// </summary>
        Change = 2,

        /// <summary>
        /// Interested in delete events
        /// </summary>
        Delete = 4,

    }
}
