name: 'Lint'
description: 'Lint Python code'

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-lint-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-lint-

    - name: Upgrade Pip
      run: python -m pip install -U pip
      shell: bash

    # For faster/better builds of sdists.
    - name: Install build pre-requisite
      run: python -m pip install wheel
      shell: bash

    - name: Install nox
      run: python -m pip install nox
      shell: bash

    - name: Check linting and formatting
      run: python -m nox --session lint
      shell: bash

    - name: Rust Tool Chain setup
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt

    - name: Rustfmt Check
      uses: actions-rust-lang/rustfmt@v1
      with:
        manifest-path: packages/rust/lsprotocol/Cargo.toml

    - name: Dotnet Tool Chain setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Dotnet Format Check
      run: dotnet format packages/dotnet/lsprotocol/lsprotocol.csproj --verify-no-changes
      shell: bash
