name: Push Validation

on:
  push:
    branches:
      - 'main'
      - 'release'
      - 'release/*'
      - 'release-*'

jobs:
  build-vsix:
    name: Create Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Packages
        uses: ./.github/actions/build-package

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        uses: ./.github/actions/lint

  python-tests:
    name: Python Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Update pip, install wheel and nox
        run: python -m pip install -U pip wheel nox
        shell: bash

      - name: Run tests
        run: python -m nox --session tests
        shell: bash

  dotnet-tests:
    name: Dotnet Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Dotnet Tool Chain setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install Generator
        run: python -m pip install -r ./requirements.txt

      - name: Generate Test Data
        run: python -m generator --plugin testdata

      - name: Generate C# Code
        run: python -m generator --plugin dotnet

      - name: Dotnet Run Tests
        run: dotnet test tests/dotnet/lsprotocol_tests/lsprotocol_tests.csproj
        shell: bash
        env:
          LSP_TEST_DATA_PATH: ${{ github.workspace }}/packages/testdata
