name: LSP Updater

on:
  schedule:
    - cron: '0 10 * * 1-5' # 10AM UTC (2AM PDT) MON-FRI

jobs:
  update-lsp:
    name: Update packages using latest LSP spec
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Update pip, install wheel and nox
        run: python -m pip install -U pip wheel nox PyGithub
        shell: bash

      - name: Run Updater
        run: python ./.github/workflows/lsp_updater.py
